image: node:24

default:
  interruptible: true
  before_script:
    - apt-get update
    - apt-get install -y git
    - corepack enable

stages:
  - test
  - docs

test:
  stage: test
  timeout: 2 minutes
  script:
    - pnpm test
  services:
    - postgres:16
  variables:
    DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    POSTGRES_HOST_AUTH_METHOD: trust
  artifacts:
    when: always
    paths:
      - deno-test.xml
    reports:
      junit: deno-test.xml

pages:
  stage: docs
  timeout: 2 minutes
  script:
    - npx deno task docs:build
    - mv docs/.vitepress/dist public
  artifacts:
    paths:
      - public
  only:
    variables:
      - $CI_DEFAULT_BRANCH == $CI_COMMIT_REF_NAME
