image: denoland/deno:1.41.1

default:
  interruptible: true
  services:
    - postgres

variables:
  POSTGRES_DB: nostrify-ndatabase-pg-testing
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: '1234'
  POSTGRES_HOST_AUTH_METHOD: trust

stages:
  - test

fmt:
  stage: test
  script: deno fmt --check

lint:
  stage: test
  script: deno lint

test:
  stage: test
  script: deno task test
