image: denoland/deno:1.44.2

default:
  interruptible: true

stages:
  - test

fmt:
  stage: test
  script: deno fmt --check

lint:
  stage: test
  script: deno lint

test:
  stage: test
  script: deno task test
  services:
    - postgres:16
  variables:
    DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    POSTGRES_HOST_AUTH_METHOD: trust
  artifacts:
    when: always
    paths:
      - deno-test.xml
    reports:
      junit: deno-test.xml
