image: denoland/deno:1.45.5

default:
  interruptible: true

stages:
  - test

fmt:
  stage: test
  script: deno fmt --check

lint:
  stage: test
  script: deno lint

test:
  stage: test
  script: deno task test
  artifacts:
    when: always
    paths:
      - deno-test.xml
    reports:
      junit: deno-test.xml

postgres:
  stage: test
  before_script:
    - bash -c 'while !</dev/tcp/postgres/5432; do sleep 1; done'
  script: deno task test packages/db
  services:
    - postgres:16
  variables:
    DATABASE_URL: postgres://postgres:postgres@postgres:5432/postgres
    POSTGRES_HOST_AUTH_METHOD: trust
